spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jw_blog?serverTimezone=Asia/Seoul
    username: jw
    password: jw1234

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 74372070425-kuo663g3tmv9gs5mf42c8al10rch9tp1.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          naver:
            client-id: CDR7h_dMBAQ6PYwP2qiI
            client-secret: E1y0DB0xAz
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


file:
  dir: C:/Users/nolan/springfile/

jw:
  key: jw1234