spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jw_blog?serverTimezone=Asia/Seoul
    username: jw
    password: jw1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
# show_sql: true
format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace